// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moonlight.ApiServer.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Moonlight.ApiServer.Database.Migrations
{
    [DbContext(typeof(CoreDataContext))]
    [Migration("20250819195904_RemovedHangfire")]
    partial class RemovedHangfire
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Moonlight.ApiServer.Database.Entities.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string[]>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Core_ApiKeys", (string)null);
                });

            modelBuilder.Entity("Moonlight.ApiServer.Database.Entities.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DonateUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpdateUrl")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Core_Themes", (string)null);
                });

            modelBuilder.Entity("Moonlight.ApiServer.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Permissions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("TokenValidTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Core_Users", (string)null);
                });

            modelBuilder.Entity("Moonlight.ApiServer.Database.Entities.Theme", b =>
                {
                    b.OwnsOne("Moonlight.ApiServer.Models.ApplicationTheme", "Content", b1 =>
                        {
                            b1.Property<int>("ThemeId")
                                .HasColumnType("integer");

                            b1.Property<float>("Border")
                                .HasColumnType("real");

                            b1.Property<string>("ColorAccent")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorAccentContent")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorBackground")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorBase100")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorBase150")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorBase200")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorBase250")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorBase300")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorBaseContent")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorError")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorErrorContent")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorInfo")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorInfoContent")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorNeutral")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorNeutralContent")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorPrimary")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorPrimaryContent")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorSecondary")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorSecondaryContent")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorSuccess")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorSuccessContent")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorWarning")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ColorWarningContent")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Depth")
                                .HasColumnType("integer");

                            b1.Property<int>("Noise")
                                .HasColumnType("integer");

                            b1.Property<float>("RadiusBox")
                                .HasColumnType("real");

                            b1.Property<float>("RadiusField")
                                .HasColumnType("real");

                            b1.Property<float>("RadiusSelector")
                                .HasColumnType("real");

                            b1.Property<float>("SizeField")
                                .HasColumnType("real");

                            b1.Property<float>("SizeSelector")
                                .HasColumnType("real");

                            b1.HasKey("ThemeId");

                            b1.ToTable("Core_Themes");

                            b1.ToJson("Content");

                            b1.WithOwner()
                                .HasForeignKey("ThemeId");
                        });

                    b.Navigation("Content")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
