name: Feature Request
description: Suggest a new feature or improvement for the software.
labels: [feature request]
body:
- type: checkboxes
  attributes:
    label: Is there an existing feature request for this?
    description: Please [search here](https://github.com/Moonlight-Panel/Moonlight/issues?q=is%3Aissue) to see if someone else has already suggested this.
    options:
    - label: I have searched the existing issues before opening this feature request.
      required: true

- type: textarea
  attributes:
    label: Describe the feature you would like to see.
    description: "A clear & concise description of the feature you'd like to have added, and what issues it would solve."
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the solution you'd like.
    description: "You must explain how you'd like to see this feature implemented. Technical implementation details are not necessary, rather an idea of how you'd like to see this feature used."
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional context to this request.
    description: "Add any other context or screenshots about the feature request."
  validations:
    required: false