<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DefaultItemExcludes>
            **\bin\**;**\obj\**;**\node_modules\**;**\Styles\*.json
        </DefaultItemExcludes>
    <StaticWebAssetsEnabled>True</StaticWebAssetsEnabled>
  </PropertyGroup>
  <PropertyGroup>
    <PackageTags>frontend</PackageTags>
    <PackageId>Moonlight.Client</PackageId>
    <Version>2.1.10</Version>
    <Authors>Moonlight Panel</Authors>
    <Description>A build of the client for moonlight development</Description>
    <PackageProjectUrl>https://github.com/Moonlight-Panel/Moonlight</PackageProjectUrl>
    <DevelopmentDependency>true</DevelopmentDependency>
    <IsPackable>true</IsPackable>
    <CompressionEnabled>false</CompressionEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Blazor-ApexCharts" Version="6.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.8" />
    <PackageReference Include="MoonCore" Version="2.0.0" />
    <PackageReference Include="MoonCore.Blazor.FlyonUi" Version="1.2.4" />
    <PackageReference Include="System.Security.Claims" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="storage\**\*" />
    <Content Remove="storage\**\*" />
    <None Remove="storage\**\*" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Moonlight.Shared\Moonlight.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Styles/mappings/*.map" Pack="true" PackagePath="Styles/" />
    <None Include="Moonlight.Client.targets" Pack="true" PackagePath="build/Moonlight.Client.targets" />
  </ItemGroup>
</Project>