<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Razor">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Moonlight.Shared\Moonlight.Shared.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Database\Migrations\"/>
    </ItemGroup>
    <PropertyGroup>
        <PackageId>Moonlight.ApiServer</PackageId>
        <Version>2.1.10</Version>
        <Authors>Moonlight Panel</Authors>
        <Description>A build of the api server for moonlight development</Description>
        <PackageProjectUrl>https://github.com/Moonlight-Panel/Moonlight</PackageProjectUrl>
        <DevelopmentDependency>true</DevelopmentDependency>
        <PackageTags>apiserver</PackageTags>
        <IsPackable>true</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Hangfire.AspNetCore" Version="1.8.20"/>
        <PackageReference Include="Hangfire.Core" Version="1.8.20"/>
        <PackageReference Include="Hangfire.EntityFrameworkCore" Version="0.7.0"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="9.0.9" />
        <PackageReference Include="MoonCore" Version="1.9.9" />
        <PackageReference Include="MoonCore.Extended" Version="1.3.8" />
        <PackageReference Include="MoonCore.PluginFramework.Generator" Version="1.0.2"/>
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.12.0" />
        <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.12.0-beta.1"/>
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.12.0"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.12.0"/>
        <PackageReference Include="Riok.Mapperly" Version="4.3.0-next.3" />
        <PackageReference Include="SharpZipLib" Version="1.4.2"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.4" />
        <PackageReference Include="Ben.Demystifier" Version="0.4.1"/>
    </ItemGroup>
</Project>