name: Development Build

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: [ "v2" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login into docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PW }}
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Moonlight/Dockerfile
          push: true
          tags: moonlightpanel/moonlight:dev
          platforms: linux/amd64,linux/arm64
          build-args: |
            "BUILD_CHANNEL=${GITHUB_REF#refs/heads/}"
            "BUILD_COMMIT_HASH=${git rev-parse --short '$GITHUB_SHA'}"
            "BUILD_NAME=devbuild ${date}"
            "BUILD_VERSION=${git rev-parse --short '$GITHUB_SHA'}"