name: Development Build

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: [ "v2" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login into docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PW }}
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Moonlight/Dockerfile
          push: true
          tags: moonlightpanel/moonlight:dev
          platforms: linux/amd64,linux/arm64
          build-args: |
            "BUILD_CHANNEL=${{github.ref_name}}"
            "BUILD_COMMIT_HASH=${{github.sha}}
            "BUILD_NAME=devbuild ${{steps.date.outputs.date}}"
            "BUILD_VERSION=unknown"
