name: Build and Publish NuGet Package

on:
  push:
    branches: [ v2_ChangeArchitecture,v2.1 ]
  workflow_dispatch:

jobs:
  build-scrips:
    runs-on: debian-12

    steps:
      - name: Clean up Environment
        run: rm -rf ./*
          rm -rf ./.??*

      - uses: actions/checkout@v3

      - name: Pack cli Scrips
        run: dotnet pack Resources/Scripts/Scripts.csproj -c Debug -o ./packs

      - name: Publish to github Pkg
        run: dotnet nuget push "./packs/*.nupkg" --skip-duplicate --api-key ${{secrets.GH_PACKAGES_READWRITE}} --source https://nuget.pkg.github.com/Moonlight-Panel/index.json

  build-moonlight:
    runs-on: debian-12
    needs: build-scrips

    steps:
      - name: Clean up Environment
        run: |
            rm -rf ./*
            rm -rf ./.??*
          
      - name: Remove nuget source
        continue-on-error: true
        run: dotnet nuget remove source moonlight-github

      - uses: actions/checkout@v3

      - name: Add nuget source
        run: dotnet nuget add source -n moonlight-github "https://nuget.pkg.github.com/Moonlight-Panel/index.json" -u Moonlight-Panel -p ${{secrets.GH_PACKAGES_READWRITE}} --store-password-in-clear-text

      - name: Setup Environment
        run: dotnet tool install dotnet-moonlight -g

      - name: Build and Pack Moonlight
        run: |
            mkdir ./packs
            export PATH="$PATH:~/.dotnet/tools"
            dotnet moonlight pack . ./packs

      - name: Publish to Github
        run: dotnet nuget push "./packs/*.nupkg" --skip-duplicate --api-key ${{secrets.GH_PACKAGES_READWRITE}} --source https://nuget.pkg.github.com/Moonlight-Panel/index.json

      - name: Remove nuget source
        continue-on-error: true
        run: dotnet nuget remove source moonlight-github