name: Build and Publish NuGet Package

on:
  push:
    branches: [ v2_ChangeArchitecture,v2.1 ]
  workflow_dispatch:

jobs:
  build-scripts:
    runs-on: debian-12

    steps:
      - name: Clean up Environment
        run: |
          rm -rf ./*
          rm -rf ./.??*

      - uses: actions/checkout@v3

      - name: Pack cli Scrips
        run: dotnet pack Resources/Scripts/Scripts.csproj -c Debug -o ./packs

      - name: Publish to github Pkg
        run: dotnet nuget push "./packs/*.nupkg" --skip-duplicate --api-key ${{secrets.GH_PACKAGES_READWRITE}} --source https://nuget.pkg.github.com/Moonlight-Panel/index.json

  build-moonlight:
    runs-on: debian-12
    needs: build-scripts

    steps:
      - name: Clean up Environment
        run: |
          rm -rf ./*
          rm -rf ./.??*

      - name: Remove nuget source
        continue-on-error: true
        run: dotnet nuget remove source moonlight-github

      - uses: actions/checkout@v3

      - name: Build and Pack Moonlight
        run: |
          mkdir ./packs
          dotnet restore
          dotnet build
          dotnet pack -o ./packs -c Debug Moonlight.ApiServer
          dotnet pack -o ./packs -c Debug Moonlight.Client
          dotnet pack -o ./packs -c Debug Moonlight.Shared

      - name: Publish to Github
        run: dotnet nuget push "./packs/*.nupkg" --skip-duplicate --api-key ${{secrets.GH_PACKAGES_READWRITE}} --source https://nuget.pkg.github.com/Moonlight-Panel/index.json

      - name: Remove nuget source
        continue-on-error: true
        run: dotnet nuget remove source moonlight-github